#!/bin/bash
Raamesh
cd Raameshiot
wget https://github.com/RaameshS/IOT.GoogleMini/archive/master.zip
unzip master.zip
cd IOT.GoogleMini-master
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
unzip ngrok-stable-linux-arm.zip

